name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: Install dependencies
        run: bundle install
      - name: Build gem
        run: rake build
      # Enable this section to allow debugging via SSH
      #- name: Setup upterm session
        #uses: lhotari/action-upterm@v1
        #with:
          ### limits ssh access and adds the ssh public key for the user which triggered the workflow
          #limit-access-to-actor: true
      - name: Install gem
        run: cd pkg && gem install --local *.gem
      - name: Run unit tests
        run: bundle exec rspec spec/ruby_snowflake/client/http_connection_wrapper_spec.rb spec/ruby_snowflake/client/key_pair_jwt_auth_manager_spec.rb
